### ISSUE TITLE
User guide docs for Consent Management 

### ISSUE THREAD

**Issue by whlowe** [GluuFederation/docs-casa-prod#14]
We need user-guide content on how to use consent management plugin. Currently there is no reference to the user-facing side, only the admin side.

**Comment by whlowe** [comment]
Hi @shmorri, I was thinking we need to add user guide content to the user guide section of the docs, i.e. https://gluu.org/docs/casa/user-guide/

We may want to re-organize the docs structure a bit so that Plugins are a subsection of the admin guide, and in those docs it covers the admin side, i.e. setting up the plugin. It should have a section for User Guide, that simply links to the user guide section of the docs. 

I think this differentiation would be a little bit more clear. Feel free to reach out to me to discuss.

**Comment by whlowe** [comment]
https://github.com/GluuFederation/docs-casa-prod/issues/16

**Comment by shmorri** [comment]
Added into User Guide
