### ISSUE TITLE
User guide docs for Account Linking

### ISSUE THREAD

**Issue by whlowe** [GluuFederation/docs-casa-prod#15]
We need user-guide content on how to use account linking plugin. Currently there is no reference to the user-facing side, only the admin side.

**Comment by shmorri** [comment]
https://github.com/GluuFederation/docs-casa-prod/blob/3.1.6/docs/source/plugins/account-linking.md#user-guide

Added here

**Comment by whlowe** [comment]
Same thing as https://github.com/GluuFederation/docs-casa-prod/issues/14#issuecomment-476433259

I'm going to open a new issue for this as well

**Comment by whlowe** [comment]
https://github.com/GluuFederation/docs-casa-prod/issues/16

**Comment by shmorri** [comment]
Added into User Guide
