### ISSUE TITLE
Configure Casa section a bit unclear

### ISSUE THREAD

**Issue by whlowe** [GluuFederation/docs-casa-prod#3]
https://github.com/GluuFederation/docs-casa-prod/blob/3.1.4/3.1.4/source/administration/admin-console.md#configure-casa

A couple lines not totally clear to me..

> You can assign the handler plugin for each method. Choose "System" to use the default implementation provided by the application.

What do you mean by default implementation provided by the app? What are the alternatives to system handler? This is actually something I've been wondering.  

> These widgets are listed in decreasing order of level, that is, the first method shown will be that with the highest level assigned in its corresponding interception script.

Can you clarify what is meant by level? Does that reference ACR Level? How does that impact the user experience?

**Comment by shmorri** [comment]
Added clarification
